version: '3'
services:
  l9vitedev-nginx:
    container_name: "l9vitedev-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - l9vitedev-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  l9vitedev-app:
    container_name: "l9vitedev-app"
    build:
      context: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      # - /src/node_modules
      # - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
